export const FETCH_ZONELIST_REQUEST = 'FETCH_ZONELIST_REQUEST'
export const FETCH_PROJECTINFO_REQUEST = 'FETCH_PROJECTINFO_REQUEST'
export const FETCH_PERMISSIONINFO_REQUEST = 'FETCH_PERMISSIONINFO_REQUEST'

export const SET_ZONE_INFO = 'SET_ZONE_INFO'
export const SET_PERMISSION_INFO = 'SET_PERMISSION_INFO'
export const SET_ZONELIST = 'SET_ZONELIST'
export const SET_PROJECTINFO = 'SET_PROJECTINFO'
export const SET_USER_DATA = 'SET_USER_DATA'
